# Generated by Django 5.1.4 on 2024-12-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('userId', models.IntegerField()),
                ('body', models.TextField()),
            ],
        ),
    ]
